//! Backend-neutral exact values, validated records, canonical projections and trusted I/O contracts.
//! No parser/executor, provider factory, environment reads or permission-bearing JSON.
pub mod acquisition;
pub mod admission;
pub mod artifact;
pub mod canonical;
pub mod claim;
pub mod classification;
pub mod contracts;
pub mod error;
pub mod evidence;
pub mod function_manifest;
pub mod function_stream;
pub mod id;
pub mod limits;
pub mod number;
pub mod ontology_catalog;
pub mod policy;
pub mod preparation;
pub mod projection;
pub mod record_codec;
pub mod recording;
pub mod recording_v3;
pub mod recording_v4;
pub mod recording_v5;
pub mod replay;
pub mod review;
pub mod semantic_admission;
pub mod snapshot;
pub mod source;
pub mod source_representation;
pub mod storage_origin;
pub mod time;
pub mod value;
pub use error::{Error, ErrorKind, Result};
pub use limits::Limits;
pub use number::ExactNumber;
pub use time::Timestamp;
pub use value::{CanonicalValue, Lookup};
